# Generated by Django 5.1 on 2024-10-26 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='clinical_level',
            field=models.CharField(default='Paramedic', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='employer',
            field=models.CharField(default='Ambulance', max_length=50),
            preserve_default=False,
        ),
    ]
