# Generated by Django 5.1 on 2024-09-17 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_projects_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=40)),
                ('age', models.IntegerField()),
                ('employer', models.TextField()),
                ('clinical_level', models.TextField()),
                ('years_experience', models.CharField(max_length=20)),
                ('email', models.TextField()),
                ('phone_number', models.CharField(max_length=10)),
                ('postcode', models.CharField(max_length=10)),
                ('is_open', models.BooleanField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
