# Generated by Django 5.1 on 2025-02-23 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_remove_pledge_anonymous_pledge_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pledge',
            name='date_created',
        ),
    ]
